# Generated by Django 4.2.5 on 2023-11-08 18:48

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0005_feedback_name_squashed_0008_statuslog_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("GET", "получено"),
                    ("PROCESSING", "в обработке"),
                    ("OK", "ответ дан"),
                ],
                default="GET",
                max_length=11,
                verbose_name="статус",
            ),
        ),
    ]
