# Generated by Django 4.2.5 on 2023-11-09 20:40

from django.db import migrations, models
import django.db.models.deletion

import feedback.models

__all__ = []


class Migration(migrations.Migration):
    replaces = [
        ("feedback", "0010_feedbackfile"),
        ("feedback", "0011_personaldata_remove_feedback_mail_and_more"),
        ("feedback", "0012_alter_personaldata_options"),
        ("feedback", "0013_alter_feedback_personal_data"),
        ("feedback", "0014_alter_feedback_personal_data"),
        ("feedback", "0015_remove_feedback_personal_data_and_more"),
    ]

    dependencies = [
        ("feedback", "0009_alter_feedback_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.FeedbackFile.create_path,
                        verbose_name="файл",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        related_query_name="files",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(max_length=150, verbose_name="почта"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "personal_data",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data",
                        related_query_name="personal_data",
                        to="feedback.feedback",
                        verbose_name="личные данные",
                    ),
                ),
            ],
            options={
                "verbose_name": "личные данные",
                "verbose_name_plural": "личные данные",
            },
        ),
    ]
