# Generated by Django 4.2.5 on 2023-11-21 16:44

from django.db import migrations, models
import django.db.models.deletion

__all__ = []


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "catalog",
            "0013_alter_category_normalized_name_and_"
            "more_squashed_0017_alter_item_date_created_alter_"
            "item_date_updated",
        ),
        (
            "users",
            "0003_profile_attempts_count_squashed_0004_profile_date_"
            "blocked_squashed_0005_rename_date_blocked_profile_"
            "block_date",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Ненависть"),
                            ("2", "Неприязнь"),
                            ("3", "Нейтрально"),
                            ("4", "Обожание"),
                            ("5", "Любовь"),
                        ],
                        max_length=11,
                        null=True,
                        verbose_name="оценка",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_item_id",
                        related_query_name="rating_item_id",
                        to="catalog.item",
                        verbose_name="оцененный товар",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_user_id",
                        related_query_name="rating_user_id",
                        to="users.user",
                        verbose_name="оценивший пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
            },
        ),
    ]
