# Generated by Django 4.2.5 on 2023-11-21 18:51

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ненависть", "1"),
                    ("Неприязнь", "2"),
                    ("Нейтрально", "3"),
                    ("Обожание", "4"),
                    ("Любовь", "5"),
                ],
                max_length=11,
                null=True,
                verbose_name="оценка",
            ),
        ),
    ]
