# Generated by Django 4.2.5 on 2023-11-21 19:27

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0003_alter_rating_item_alter_rating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                null=True,
                verbose_name="оценка",
            ),
        ),
    ]
