# Generated by Django 4.2.5 on 2023-11-23 19:53

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0004_alter_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="last_change",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
