# Generated by Django 4.2.5 on 2023-10-26 15:31

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    replaces = [
        ("catalog", "0002_alter_itemmainimage_image"),
        ("catalog", "0003_alter_itemmainimage_image"),
    ]

    dependencies = [
        ("catalog", "0001_0012_0016_0017_0019_0025_0030_0018_0002_0003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=models.ImageField(
                default="Дефолт значение",
                help_text="Выберите главно изображение",
                upload_to="catalog/images/main_item_images/%Y.%m.%d",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=models.ImageField(
                default="Дефолт значение",
                help_text="Выберите главное изображение",
                upload_to="catalog/images/main_item_images/%Y.%m.%d",
                verbose_name="главное изображение",
            ),
        ),
    ]
