# Generated by Django 4.2.5 on 2023-10-31 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models

import catalog.validators

__all__ = []


class Migration(migrations.Migration):
    replaces = [
        (
            "catalog",
            "0004_alter_category_slug_squashed_0005_alter_category_slug",
        ),
        ("catalog", "0006_alter_item_text"),
        ("catalog", "0007_alter_item_image"),
        (
            "catalog",
            "0008_remove_item_image_itemmainimage_main_image_and_more",
        ),
        ("catalog", "0009_item_is_on_main_alter_itemmainimage_main_image"),
        ("catalog", "0010_alter_item_tags"),
    ]

    dependencies = [
        (
            "catalog",
            "0002_alter_itemmainimage_image_squashed"
            "_0003_alter_itemmainimage_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Отображаемо название",
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Отображаемое название",
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                default="",
                help_text="Опишите объект, описание должно содержать"
                " слово 'роскошно' или 'превосходно'",
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    catalog.validators.custom_validator,
                    catalog.validators.ValidateMustContain(
                        "превосходно",
                        "роскошно",
                    ),
                ],
                verbose_name="текст",
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="itemimagegallery",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="состояние видимости с главной страницы",
                verbose_name="На главной",
            ),
        ),
        migrations.AddField(
            model_name="itemmainimage",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="catalog.item",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
    ]
