# Generated by Django 4.2.5 on 2023-10-31 20:12

from django.db import migrations, models
import django.db.models.deletion


__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0004_alter_category_slug_squashed_0005_alter_"
            "category_slug_squashed_0010_alter_item_tags",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
                verbose_name="главное изображение",
            ),
        ),
    ]
