# Generated by Django 4.2.5 on 2023-10-31 20:25

from django.db import migrations, models
import django.db.models.deletion


__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_alter_itemmainimage_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="mimage",
                to="catalog.item",
                verbose_name="главное изображение",
            ),
        ),
    ]
