# Generated by Django 4.2.5 on 2023-11-07 14:34

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    replaces = [
        ("catalog", "0013_alter_category_normalized_name_and_more"),
        (
            "catalog",
            "0014_item_date_created_squashed_0016_rename_"
            "date_changed_item_date_updated",
        ),
        ("catalog", "0017_alter_item_date_created_alter_item_date_updated"),
    ]

    dependencies = [
        ("catalog", "0012_alter_itemmainimage_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
