# Generated by Django 4.2.5 on 2023-11-15 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

__all__ = []


class Migration(migrations.Migration):
    replaces = [
        (
            "users",
            "0001_initial_squashed_0003_alter_profile_"
            "image_squashed_0005_alter_profile_birthday_alter"
            "_profile_image",
        ),
        ("users", "0006_alter_profile_user"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="день рождения",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="аватарка",
                    ),
                ),
                (
                    "coffee_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="выпито кофе",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        related_query_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное поле",
                "verbose_name_plural": "Дополнительные поля",
            },
        ),
    ]
