# Generated by Django 4.2.5 on 2023-11-16 16:50

from django.db import migrations

__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_0003_0005_0006"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
    ]
