# Generated by Django 4.2.5 on 2023-11-17 20:07

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    replaces = [
        (
            "users",
            "0003_profile_attempts_count_squashed_0004_profile_date_blocked",
        ),
        ("users", "0005_rename_date_blocked_profile_block_date"),
    ]

    dependencies = [
        ("users", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="попыток входа",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="block_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="время блокировки",
            ),
        ),
    ]
